[package]
name = "programme"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.10"

[dev-dependencies]
solana-program-test = "2.0.10"
solana-sdk="2.0.10"

[lib]
crate-type=["cdylib","lib"]